import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';

@Injectable()
export class StoreProvider {
  stores: any[];
  constructor() {
    this.stores = [
  {
    "ClientID": 2073,
    "ClientCode": "C1013",
    "PSCName": "HNL PSC Allentown Medical Center",
    "AddressLine": "500 North 7th Street",
    "AddressLine2": "Ste. 108",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Allentown",
    "State": "PA",
    "ZipCode": "18102",
    "Phone": "(610) 969-2790",
    "Fax": "(610) 969-3085",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 7:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 7:00 p.m.</span>  Friday: 7:00 a.m. to 7:00 p.m.  Saturday: Closed  Sunday: 10:00 a.m. to 2:00 p.m.",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_amc.jpg",
    "Distance": -1,
    "Latitude": 40.6092,
    "Longitude": -75.475,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6831,
    "ClientCode": "C5776",
    "PSCName": "HNL PSC Allentown Towne Center (TILGHMAN)",
    "AddressLine": "4727 Tilghman Street",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Allentown",
    "State": "PA",
    "ZipCode": "18104",
    "Phone": "(610) 841-3770",
    "Fax": "(610) 841-3789",
    "BussinessHours": "  Monday: 6:00 a.m. to 6:00 p.m.  Tuesday: 6:00 a.m. to 6:00 p.m.  Wednesday: 6:00 a.m. to 6:00 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 6:00 p.m.</span>  Friday: 6:00 a.m. to 6:00 p.m.  Saturday: Closed  Sunday: 7:00 a.m. to 11:00 a.m.",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_AllentownTilghman.jpg",
    "Distance": -1,
    "Latitude": 40.5896,
    "Longitude": -75.5625,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 4365,
    "ClientCode": "C3083",
    "PSCName": "HNL PSC Brodheadsville",
    "AddressLine": "111 Switzgable Drive",
    "AddressLine2": "Coordinated Health Building",
    "AddressLine3": null,
    "County": "Monroe County",
    "Country": null,
    "City": "Brodheadsville",
    "State": "PA",
    "ZipCode": "18322",
    "Phone": "(570) 992-4322",
    "Fax": "(570) 992-4289",
    "BussinessHours": "  Monday: 6:30 a.m. to 4:30 p.m.  Tuesday: 6:30 a.m. to 4:30 p.m.  Wednesday: 6:30 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 4:30 p.m.</span>  Friday: 6:30 a.m. to 4:30 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_brodheadsville.jpg",
    "Distance": -1,
    "Latitude": 40.925,
    "Longitude": -75.4026,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 4307,
    "ClientCode": "C3032",
    "PSCName": "HNL PSC Carlisle",
    "AddressLine": "1200 Walnut Bottom Road",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Cumberland County",
    "Country": null,
    "City": "Carlisle",
    "State": "PA",
    "ZipCode": "17015",
    "Phone": "(717) 243-2634",
    "Fax": "(717) 243-3486",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:00 p.m.</span>  Friday: 7:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_carlisle.jpg",
    "Distance": -1,
    "Latitude": 40.1786,
    "Longitude": -77.2196,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "20",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 3680,
    "ClientCode": "C2459",
    "PSCName": "HNL PSC Cedar Crest Boulevard",
    "AddressLine": "1251 South Cedar Crest Boulevard",
    "AddressLine2": "Ste. 103C",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Allentown",
    "State": "PA",
    "ZipCode": "18103",
    "Phone": "(610) 434-5577",
    "Fax": "(610) 434-9245",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:30 p.m.  Tuesday: 7:00 a.m. to 5:30 p.m.  Wednesday: 7:00 a.m. to 5:30 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:30 p.m.</span>  Friday: 7:00 a.m. to 5:30 p.m.  Saturday: 7:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_1251.jpg",
    "Distance": -1,
    "Latitude": 40.5658,
    "Longitude": -75.517,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 5840,
    "ClientCode": "C4682",
    "PSCName": "HNL PSC Chambersburg",
    "AddressLine": "465 Phoenix Drive",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Franklin County",
    "Country": null,
    "City": "Chambersburg",
    "State": "PA",
    "ZipCode": "17201",
    "Phone": "(717) 414-7452",
    "Fax": "(717) 414-7459",
    "BussinessHours": "  Monday: 6:00 a.m. to 3:30 p.m.  Tuesday: 6:00 a.m. to 3:30 p.m.  Wednesday: 6:00 a.m. to 3:30 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 3:30 p.m.</span>  Friday: 6:00 a.m. to 3:30 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_chambersburg.jpg",
    "Distance": -1,
    "Latitude": 39.9343,
    "Longitude": -77.6353,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6356,
    "ClientCode": "C5180",
    "PSCName": "HNL PSC Crest Plaza",
    "AddressLine": "1630 North Cedar Crest Boulevard",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Allentown",
    "State": "PA",
    "ZipCode": "18104",
    "Phone": "(484) 664-7291",
    "Fax": "(484) 664-7293",
    "BussinessHours": "  Monday: 6:30 a.m. to 8:00 p.m.  Tuesday: 6:30 a.m. to 8:00 p.m.  Wednesday: 6:30 a.m. to 8:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 8:00 p.m.</span>  Friday: 6:30 a.m. to 8:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_atowncrestplaza.jpg",
    "Distance": -1,
    "Latitude": 40.6139,
    "Longitude": -75.5331,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6324,
    "ClientCode": "C5147",
    "PSCName": "HNL PSC Crossroads of Nazareth",
    "AddressLine": "3465 Nazareth Road",
    "AddressLine2": "Ste. 101",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Easton",
    "State": "PA",
    "ZipCode": "18045",
    "Phone": "(610) 559-1501",
    "Fax": "(610) 559-9122",
    "BussinessHours": "  Monday: 6:30 a.m. to 4:30 p.m.  Tuesday: 6:30 a.m. to 4:30 p.m.  Wednesday: 6:30 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 4:30 p.m.</span>  Friday: 6:30 a.m. to 4:30 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/57cd9bcf-b079-4683-afdc-db3a03164b0e_psc_eastonnorthwood2011.jpg",
    "Distance": -1,
    "Latitude": 40.7062,
    "Longitude": -75.2747,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6167,
    "ClientCode": "C5003",
    "PSCName": "HNL PSC Downingtown",
    "AddressLine": "797 East Lancaster Avenue",
    "AddressLine2": "Downingtown Professional Plaza, Ste. 1A",
    "AddressLine3": null,
    "County": "Chester County",
    "Country": null,
    "City": "Downingtown",
    "State": "PA",
    "ZipCode": "19335",
    "Phone": "(484) 237-8957",
    "Fax": "(484) 593-0000",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:00 p.m.  Tuesday: 7:00 a.m. to 4:00 p.m.  Wednesday: 7:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:00 p.m.</span>  Friday: 7:00 a.m. to 4:00 p.m.  Saturday: 8:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Downingtown.jpg",
    "Distance": -1,
    "Latitude": 40.0155,
    "Longitude": -75.6891,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6049,
    "ClientCode": "C4895",
    "PSCName": "HNL PSC East Stroudsburg",
    "AddressLine": "505 Independence Road",
    "AddressLine2": "Coordinated Health Building",
    "AddressLine3": null,
    "County": "Monroe County",
    "Country": null,
    "City": "East Stroudsburg",
    "State": "PA",
    "ZipCode": "18301",
    "Phone": "(570) 730-4970",
    "Fax": "(570) 730-4972",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:00 p.m.</span>  Friday: 7:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_eaststroudsburg.jpg",
    "Distance": -1,
    "Latitude": 41.0062,
    "Longitude": -75.1579,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6006,
    "ClientCode": "C4854",
    "PSCName": "HNL PSC Emmaus",
    "AddressLine": "1040 Chestnut Street",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Emmaus",
    "State": "PA",
    "ZipCode": "18049",
    "Phone": "(610) 966-5353",
    "Fax": "(610) 966-5344",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:00 p.m.  Tuesday: 7:00 a.m. to 4:00 p.m.  Wednesday: 7:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:00 p.m.</span>  Friday: 7:00 a.m. to 4:00 p.m.  Saturday: 7:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_emmaus.jpg",
    "Distance": -1,
    "Latitude": 40.5288,
    "Longitude": -75.5052,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "25",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6950,
    "ClientCode": "C5913",
    "PSCName": "HNL PSC Fountainville",
    "AddressLine": "4949 Swamp Road",
    "AddressLine2": "Ste. 107",
    "AddressLine3": null,
    "County": "Bucks County",
    "Country": null,
    "City": "Doylestown",
    "State": "PA",
    "ZipCode": "18901",
    "Phone": "(267) 454-7667",
    "Fax": "(267) 454-7920",
    "BussinessHours": "  Monday: 6:30 a.m. to 7:30 p.m.  Tuesday: 6:30 a.m. to 7:30 p.m.  Wednesday: 6:30 a.m. to 7:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 7:30 p.m.</span>  Friday: 6:30 a.m. to 7:30 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Fountainville.jpg",
    "Distance": -1,
    "Latitude": 40.3409,
    "Longitude": -75.1505,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 8947,
    "ClientCode": "L638",
    "PSCName": "HNL PSC Haddon Heights",
    "AddressLine": "17 White Horse Pike",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Camden County",
    "Country": null,
    "City": "Haddon Heights",
    "State": "NJ",
    "ZipCode": "08035",
    "Phone": "(856) 547-8408",
    "Fax": "(856) 547-8493",
    "BussinessHours": "  Monday: 7:00 a.m. to 3:30 p.m.  Tuesday: 7:00 a.m. to 3:30 p.m.  Wednesday: 7:00 a.m. to 3:30 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 3:30 p.m.</span>  Friday: 7:00 a.m. to 3:30 p.m.  Saturday: 8:00 a.m. to 11:30 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_haddonheights.jpg",
    "Distance": -1,
    "Latitude": 39.886,
    "Longitude": -75.0588,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2075,
    "ClientCode": "C1015",
    "PSCName": "HNL PSC Hamburg",
    "AddressLine": "700 Hawk Ridge Drive",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Berks County",
    "Country": null,
    "City": "Hamburg",
    "State": "PA",
    "ZipCode": "19526",
    "Phone": "(610) 562-9026",
    "Fax": "(610) 562-9027",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:00 p.m.</span>  Friday: 7:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Hamburg.jpg",
    "Distance": -1,
    "Latitude": 40.5444,
    "Longitude": -75.9747,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 7102,
    "ClientCode": "C6075",
    "PSCName": "HNL PSC Harrisburg",
    "AddressLine": "845 Sir Thomas Court",
    "AddressLine2": "Ste. 6",
    "AddressLine3": null,
    "County": "Dauphin County",
    "Country": null,
    "City": "Harrisburg",
    "State": "PA",
    "ZipCode": "17109",
    "Phone": "(717) 775-1917",
    "Fax": "(717) 775-1932",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:00 p.m.  Tuesday: 7:00 a.m. to 4:00 p.m.  Wednesday: 7:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:00 p.m.</span>  Friday: 7:00 a.m. to 4:00 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_harrisburg.jpg",
    "Distance": -1,
    "Latitude": 40.2824,
    "Longitude": -76.8207,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6108,
    "ClientCode": "C4950",
    "PSCName": "HNL PSC Hausman Road",
    "AddressLine": "798 Hausman Road",
    "AddressLine2": "Ste. 150A",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Allentown",
    "State": "PA",
    "ZipCode": "18104",
    "Phone": "(610) 366-1023",
    "Fax": "(610) 366-1089",
    "BussinessHours": "  Monday: 8:00 a.m. to 4:00 p.m.  Tuesday: 8:00 a.m. to 4:00 p.m.  Wednesday: 8:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 8:00 a.m. to 4:00 p.m.</span>  Friday: 8:00 a.m. to 4:00 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_HausmanRd.jpg",
    "Distance": -1,
    "Latitude": 40.5928,
    "Longitude": -75.5634,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6739,
    "ClientCode": "C5671",
    "PSCName": "HNL PSC Health Center at Bangor",
    "AddressLine": "1337 Blue Valley Drive",
    "AddressLine2": "Ste. 1",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Pen Argyl",
    "State": "PA",
    "ZipCode": "18072",
    "Phone": "(610) 654-1240",
    "Fax": "(610) 654-1241",
    "BussinessHours": "  Monday: 8:00 a.m. to 4:00 p.m.  Tuesday: 8:00 a.m. to 4:00 p.m.  Wednesday: 8:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 8:00 a.m. to 4:00 p.m.</span>  Friday: 8:00 a.m. to 4:00 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_BangorHealthCenter.jpg",
    "Distance": -1,
    "Latitude": 40.8742,
    "Longitude": -75.2346,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 3784,
    "ClientCode": "C2549",
    "PSCName": "HNL PSC Health Center at Bethlehem Twsp.",
    "AddressLine": "2101 Emrick Boulevard",
    "AddressLine2": "The Health Center at Bethlehem Township",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Bethlehem",
    "State": "PA",
    "ZipCode": "18020",
    "Phone": "(610) 861-9000",
    "Fax": "(610) 861-9007",
    "BussinessHours": "  Monday: 6:30 a.m. to 5:00 p.m.  Tuesday: 6:30 a.m. to 5:00 p.m.  Wednesday: 6:30 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 5:00 p.m.</span>  Friday: 6:30 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_bethlehemtownship.jpg",
    "Distance": -1,
    "Latitude": 40.6516,
    "Longitude": -75.292,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 7144,
    "ClientCode": "C6114",
    "PSCName": "HNL PSC Health Center at Fogelsville",
    "AddressLine": "1431 Nursery St.",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh",
    "Country": null,
    "City": "Fogelsville",
    "State": "PA",
    "ZipCode": "18051-1612",
    "Phone": "(610) 841-7797",
    "Fax": "(610) 841-7815",
    "BussinessHours": "  Monday: 6:00 a.m. to 5:00 p.m.  Tuesday: 6:00 a.m. to 5:00 p.m.  Wednesday: 6:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 5:00 p.m.</span>  Friday: 6:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: 7:00 a.m. to 11:00 a.m.",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_fogelsville.jpg",
    "Distance": -1,
    "Latitude": 40.584315,
    "Longitude": -75.632661,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6473,
    "ClientCode": "C5308",
    "PSCName": "HNL PSC Health Center at Moselem Springs",
    "AddressLine": "14351 Kutztown Road",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Berks County",
    "Country": null,
    "City": "Fleetwood",
    "State": "PA",
    "ZipCode": "19522",
    "Phone": "(484) 575-3709",
    "Fax": "(484) 575-3738",
    "BussinessHours": "  Monday: 6:00 a.m. to 5:00 p.m.  Tuesday: 6:00 a.m. to 5:00 p.m.  Wednesday: 6:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 5:00 p.m.</span>  Friday: 6:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/PSC_MoselemSpringsHealthCenter.jpg",
    "Distance": -1,
    "Latitude": 40.4861,
    "Longitude": -75.8385,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2205,
    "ClientCode": "C1136",
    "PSCName": "HNL PSC Hellertown",
    "AddressLine": "708 Main Street",
    "AddressLine2": "Ste.100",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Hellertown",
    "State": "PA",
    "ZipCode": "18055",
    "Phone": "(610) 748-8812",
    "Fax": "(610) 748-8814",
    "BussinessHours": "  Monday: 6:30 a.m. to 2:30 p.m.  Tuesday: 6:30 a.m. to 2:30 p.m.  Wednesday: 6:30 a.m. to 2:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 2:30 p.m.</span>  Friday: 6:30 a.m. to 2:30 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_hellertown.jpg",
    "Distance": -1,
    "Latitude": 40.5795,
    "Longitude": -75.3411,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 9984,
    "ClientCode": "C6428",
    "PSCName": "HNL PSC Jermyn",
    "AddressLine": "5 South Washington Avenue",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lackawanna County",
    "Country": null,
    "City": "Jermyn",
    "State": "PA",
    "ZipCode": "18433",
    "Phone": "(570) 876-1100",
    "Fax": "(570) 876-1107",
    "BussinessHours": "  Monday: 8:00 a.m. to 8:00 p.m.  Tuesday: 8:00 a.m. to 8:00 p.m.  Wednesday: 8:00 a.m. to 8:00 p.m.<span class=\"today\">  Thursday: 8:00 a.m. to 8:00 p.m.</span>  Friday: 8:00 a.m. to 8:00 p.m.  Saturday: 8:00 a.m. to 2:00 p.m.  Sunday: 8:00 a.m. to 12:00 p.m.",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/75f710ea-902a-47a9-9223-8198b53c00c2_PSC_Jermyn.jpg",
    "Distance": -1,
    "Latitude": 41.5161,
    "Longitude": -75.548,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "25",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2076,
    "ClientCode": "C1016",
    "PSCName": "HNL PSC Kutztown",
    "AddressLine": "333 Normal Avenue",
    "AddressLine2": "Ste. 101",
    "AddressLine3": null,
    "County": "Berks County",
    "Country": null,
    "City": "Kutztown",
    "State": "PA",
    "ZipCode": "19530",
    "Phone": "(610) 683-3999",
    "Fax": "(610) 683-9101",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:00 p.m.</span>  Friday: 7:00 a.m. to 5:00 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_kutztown.jpg",
    "Distance": -1,
    "Latitude": 40.5138,
    "Longitude": -75.7777,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2873,
    "ClientCode": "C1742",
    "PSCName": "HNL PSC Lancaster",
    "AddressLine": "272 Granite Run Drive",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lancaster County",
    "Country": null,
    "City": "Lancaster",
    "State": "PA",
    "ZipCode": "17601",
    "Phone": "(717) 560-8891",
    "Fax": "(717) 560-8893",
    "BussinessHours": "  Monday: 7:30 a.m. to 4:00 p.m.  Tuesday: 7:30 a.m. to 4:00 p.m.  Wednesday: 7:30 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:30 a.m. to 4:00 p.m.</span>  Friday: 7:30 a.m. to 4:00 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_lancaster.jpg",
    "Distance": -1,
    "Latitude": 40.0767,
    "Longitude": -76.3332,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "20",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2614,
    "ClientCode": "C1509",
    "PSCName": "HNL PSC Langhorne",
    "AddressLine": "582 Middletown Boulevard",
    "AddressLine2": "Oxford Court Business Center, Suite B-11",
    "AddressLine3": null,
    "County": "Bucks County",
    "Country": null,
    "City": "Langhorne",
    "State": "PA",
    "ZipCode": "19047",
    "Phone": "(215) 702-8107",
    "Fax": "(215) 702-8109",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:30 p.m.  Tuesday: 7:00 a.m. to 4:30 p.m.  Wednesday: 7:00 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:30 p.m.</span>  Friday: 7:00 a.m. to 4:30 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_langhorne.jpg",
    "Distance": -1,
    "Latitude": 40.1876,
    "Longitude": -74.8782,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2079,
    "ClientCode": "C1019",
    "PSCName": "HNL PSC Laurys Station",
    "AddressLine": "5649 Wynnewood Drive",
    "AddressLine2": "Ste. 204",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Laurys Station",
    "State": "PA",
    "ZipCode": "18059",
    "Phone": "(610) 262-7714",
    "Fax": "(610) 262-3968",
    "BussinessHours": "  Monday: 6:00 a.m. to 5:00 p.m.  Tuesday: 6:00 a.m. to 5:00 p.m.  Wednesday: 6:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 5:00 p.m.</span>  Friday: 6:00 a.m. to 5:00 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_laurystation.jpg",
    "Distance": -1,
    "Latitude": 40.7277,
    "Longitude": -75.5346,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 5194,
    "ClientCode": "C3974",
    "PSCName": "HNL PSC Lebanon",
    "AddressLine": "200 Schneider Drive",
    "AddressLine2": "Ste. 4",
    "AddressLine3": null,
    "County": "Lebanon County",
    "Country": null,
    "City": "Lebanon",
    "State": "PA",
    "ZipCode": "17046",
    "Phone": "(717) 273-4441",
    "Fax": "(717) 273-3583",
    "BussinessHours": "  Monday: 6:30 a.m. to 2:30 p.m.  Tuesday: 6:30 a.m. to 2:30 p.m.  Wednesday: 6:30 a.m. to 2:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 2:30 p.m.</span>  Friday: 6:30 a.m. to 2:30 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_lebanon.jpg",
    "Distance": -1,
    "Latitude": 40.3425,
    "Longitude": -76.4158,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2081,
    "ClientCode": "C1021",
    "PSCName": "HNL PSC Lehighton",
    "AddressLine": "1001 Mahoning Street",
    "AddressLine2": "Ste. 3A",
    "AddressLine3": null,
    "County": "Carbon County",
    "Country": null,
    "City": "Lehighton",
    "State": "PA",
    "ZipCode": "18235",
    "Phone": "(610) 379-9144",
    "Fax": "(610) 379-9154",
    "BussinessHours": "  Monday: 7:00 a.m. to 3:30 p.m.  Tuesday: 7:00 a.m. to 3:30 p.m.  Wednesday: 7:00 a.m. to 3:30 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 3:30 p.m.</span>  Friday: 7:00 a.m. to 3:30 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_lehighton.jpg",
    "Distance": -1,
    "Latitude": 40.8305,
    "Longitude": -75.7235,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 7118,
    "ClientCode": "C6090",
    "PSCName": "HNL PSC Lemoyne",
    "AddressLine": "717 Market Street",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Cumberland County",
    "Country": null,
    "City": "Lemoyne",
    "State": "PA",
    "ZipCode": "17043",
    "Phone": "(717) 525-7007",
    "Fax": "(717) 525-7061",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:00 p.m.  Tuesday: 7:00 a.m. to 4:00 p.m.  Wednesday: 7:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:00 p.m.</span>  Friday: 7:00 a.m. to 4:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_lemoyne.jpg",
    "Distance": -1,
    "Latitude": 40.2446,
    "Longitude": -76.9009,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6902,
    "ClientCode": "C5863",
    "PSCName": "HNL PSC North East Philadelphia",
    "AddressLine": "7265 Revere Street",
    "AddressLine2": "Revere Commons",
    "AddressLine3": null,
    "County": "Philadelphia County",
    "Country": null,
    "City": "Philadelphia",
    "State": "PA",
    "ZipCode": "19149",
    "Phone": "(267) 686-7176",
    "Fax": "(267) 686-7187",
    "BussinessHours": "  Monday: 6:30 a.m. to 3:00 p.m.  Tuesday: 6:30 a.m. to 3:00 p.m.  Wednesday: 6:30 a.m. to 3:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 3:00 p.m.</span>  Friday: 6:30 a.m. to 3:00 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_NEPhiladelphiaRev.jpg",
    "Distance": -1,
    "Latitude": 40.0433,
    "Longitude": -75.0534,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "20",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6705,
    "ClientCode": "C5616",
    "PSCName": "HNL PSC North Reading",
    "AddressLine": "3535 North 5th Street Highway",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Berks County",
    "Country": null,
    "City": "Reading",
    "State": "PA",
    "ZipCode": "19605",
    "Phone": "(610) 743-5211",
    "Fax": "(610) 743-5496",
    "BussinessHours": "  Monday: 6:30 a.m. to 4:30 p.m.  Tuesday: 6:30 a.m. to 4:30 p.m.  Wednesday: 6:30 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 4:30 p.m.</span>  Friday: 6:30 a.m. to 4:30 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_reading.jpg",
    "Distance": -1,
    "Latitude": 40.3889,
    "Longitude": -75.9271,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6059,
    "ClientCode": "C4903",
    "PSCName": "HNL PSC Northampton",
    "AddressLine": "1825 Franklin Street",
    "AddressLine2": "Tepes Plaza, Ste. C",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Northampton",
    "State": "PA",
    "ZipCode": "18067",
    "Phone": "(610) 440-2251",
    "Fax": "(610) 440-2268",
    "BussinessHours": "  Monday: 6:00 a.m. to 4:30 p.m.  Tuesday: 6:00 a.m. to 4:30 p.m.  Wednesday: 6:00 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 4:30 p.m.</span>  Friday: 6:00 a.m. to 4:30 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_northampton.jpg",
    "Distance": -1,
    "Latitude": 40.6876,
    "Longitude": -75.4988,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6179,
    "ClientCode": "C5015",
    "PSCName": "HNL PSC Peckville",
    "AddressLine": "1500 North Main Street",
    "AddressLine2": "Rosedon Plaza",
    "AddressLine3": null,
    "County": "Lackawanna County",
    "Country": null,
    "City": "Blakely",
    "State": "PA",
    "ZipCode": "18452",
    "Phone": "(570) 483-4722",
    "Fax": "(570) 483-4782",
    "BussinessHours": "  Monday: 7:00 a.m. to 3:00 p.m.  Tuesday: 7:00 a.m. to 3:00 p.m.  Wednesday: 7:00 a.m. to 3:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 3:00 p.m.</span>  Friday: 7:00 a.m. to 3:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Peckville.jpg",
    "Distance": -1,
    "Latitude": 41.4785,
    "Longitude": -75.6017,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 9985,
    "ClientCode": "C6429",
    "PSCName": "HNL PSC Pottsville",
    "AddressLine": "1504 Pennsylvania 61",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Schuylkill County",
    "Country": null,
    "City": "Pottsville",
    "State": "PA",
    "ZipCode": "17901",
    "Phone": "(570) 728-2338",
    "Fax": "(570) 728-2341",
    "BussinessHours": "  Monday: 7:00 a.m. to 3:00 p.m.  Tuesday: 7:00 a.m. to 3:00 p.m.  Wednesday: 7:00 a.m. to 3:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 3:00 p.m.</span>  Friday: 7:00 a.m. to 3:00 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/4dc8c935-f3d2-4927-a254-593c56bd3ee2_psc_pottsville.jpg",
    "Distance": -1,
    "Latitude": 40.6434,
    "Longitude": -76.1852,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 4936,
    "ClientCode": "C3667",
    "PSCName": "HNL PSC Quakertown",
    "AddressLine": "127 South 5th Street",
    "AddressLine2": "The Atrium",
    "AddressLine3": null,
    "County": "Bucks County",
    "Country": null,
    "City": "Quakertown",
    "State": "PA",
    "ZipCode": "18951",
    "Phone": "(215) 538-8505",
    "Fax": "(215) 538-8645",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:00 p.m.</span>  Friday: 7:00 a.m. to 5:00 p.m.  Saturday: 8:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_quakertown.jpg",
    "Distance": -1,
    "Latitude": 40.4394,
    "Longitude": -75.3404,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6321,
    "ClientCode": "C5144",
    "PSCName": "HNL PSC Saucon Valley",
    "AddressLine": "3800 Sierra Circle",
    "AddressLine2": "Ste. 110",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Center Valley",
    "State": "PA",
    "ZipCode": "18034",
    "Phone": "(484) 788-0394",
    "Fax": "(484) 788-0396",
    "BussinessHours": "  Monday: 6:30 a.m. to 4:30 p.m.  Tuesday: 6:30 a.m. to 4:30 p.m.  Wednesday: 6:30 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 4:30 p.m.</span>  Friday: 6:30 a.m. to 4:30 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_CenterSauconValley.jpg",
    "Distance": -1,
    "Latitude": 40.5506,
    "Longitude": -75.4261,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6756,
    "ClientCode": "C5691",
    "PSCName": "HNL PSC Schnecksville",
    "AddressLine": "5040 Pennsylvania 873",
    "AddressLine2": "Ste. F",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Schnecksville",
    "State": "PA",
    "ZipCode": "18078",
    "Phone": "(610) 799-0146",
    "Fax": "(610) 799-0148",
    "BussinessHours": "  Monday: 6:30 a.m. to 4:00 p.m.  Tuesday: 6:30 a.m. to 4:00 p.m.  Wednesday: 6:30 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 4:00 p.m.</span>  Friday: 6:30 a.m. to 4:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Schnecksville.jpg",
    "Distance": -1,
    "Latitude": 40.678,
    "Longitude": -75.6155,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 5762,
    "ClientCode": "C4596",
    "PSCName": "HNL PSC Schoenersville Road",
    "AddressLine": "3219 Schoenersville Road",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Bethlehem",
    "State": "PA",
    "ZipCode": "18017",
    "Phone": "(610) 419-9789",
    "Fax": "(610) 419-9758",
    "BussinessHours": "  Monday: 6:00 a.m. to 5:00 p.m.  Tuesday: 6:00 a.m. to 5:00 p.m.  Wednesday: 6:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:00 a.m. to 5:00 p.m.</span>  Friday: 6:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_schoenersville.jpg",
    "Distance": -1,
    "Latitude": 40.657,
    "Longitude": -75.4185,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "25",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6178,
    "ClientCode": "C5014",
    "PSCName": "HNL PSC Scranton",
    "AddressLine": "3 West Olive Street",
    "AddressLine2": "Electric City Plaza",
    "AddressLine3": null,
    "County": "Lackawanna County",
    "Country": null,
    "City": "Scranton",
    "State": "PA",
    "ZipCode": "18508",
    "Phone": "(570) 909-9085",
    "Fax": "(570) 955-0937",
    "BussinessHours": "  Monday: 7:00 a.m. to 3:00 p.m.  Tuesday: 7:00 a.m. to 3:00 p.m.  Wednesday: 7:00 a.m. to 3:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 3:00 p.m.</span>  Friday: 7:00 a.m. to 3:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Scranton.jpg",
    "Distance": -1,
    "Latitude": 41.4173,
    "Longitude": -75.6638,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 4054,
    "ClientCode": "C2797",
    "PSCName": "HNL PSC Slate Belt",
    "AddressLine": "91 Bangor Junction Road",
    "AddressLine2": "Blue Valley Plaza",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Bangor",
    "State": "PA",
    "ZipCode": "18013",
    "Phone": "(610) 599-0875",
    "Fax": "(610) 599-1288",
    "BussinessHours": "  Monday: 6:30 a.m. to 5:00 p.m.  Tuesday: 6:30 a.m. to 5:00 p.m.  Wednesday: 6:30 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 5:00 p.m.</span>  Friday: 6:30 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 12:00 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_slatebelt91.jpg",
    "Distance": -1,
    "Latitude": 40.8722,
    "Longitude": -75.2322,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 2078,
    "ClientCode": "C1018",
    "PSCName": "HNL PSC Trexlertown",
    "AddressLine": "6900 Hamilton Boulevard",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Trexlertown",
    "State": "PA",
    "ZipCode": "18087",
    "Phone": "(610) 402-0150",
    "Fax": "(610) 402-7163",
    "BussinessHours": "  Monday: 6:30 a.m. to 5:00 p.m.  Tuesday: 6:30 a.m. to 5:00 p.m.  Wednesday: 6:30 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 5:00 p.m.</span>  Friday: 6:30 a.m. to 5:00 p.m.  Saturday: 6:30 a.m. to 2:30 p.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_trexlertown.jpg",
    "Distance": -1,
    "Latitude": 40.5506,
    "Longitude": -75.5909,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6866,
    "ClientCode": "C5817",
    "PSCName": "HNL PSC Waynesboro",
    "AddressLine": "1051 East Main Street",
    "AddressLine2": "Ste. 3",
    "AddressLine3": null,
    "County": "Franklin County",
    "Country": null,
    "City": "Waynesboro",
    "State": "PA",
    "ZipCode": "17268",
    "Phone": "(717) 387-5328",
    "Fax": "(717) 387-5643",
    "BussinessHours": "  Monday: 6:30 a.m. to 2:00 p.m.  Tuesday: 6:30 a.m. to 2:00 p.m.  Wednesday: 6:30 a.m. to 2:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 2:00 p.m.</span>  Friday: 6:30 a.m. to 2:00 p.m.  Saturday: 7:00 a.m. to 9:30 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_waynesboro.jpg",
    "Distance": -1,
    "Latitude": 39.7452,
    "Longitude": -77.5553,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6991,
    "ClientCode": "C5963",
    "PSCName": "HNL PSC West Broad Street",
    "AddressLine": "529 West Broad Street",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Bethlehem",
    "State": "PA",
    "ZipCode": "18018",
    "Phone": "(610) 625-2606",
    "Fax": "(610) 625-2683",
    "BussinessHours": "  Monday: 6:30 a.m. to 5:00 p.m.  Tuesday: 6:30 a.m. to 5:00 p.m.  Wednesday: 6:30 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 5:00 p.m.</span>  Friday: 6:30 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: 7:00 a.m. to 11:00 a.m.",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_WestBroadBeth.jpg",
    "Distance": -1,
    "Latitude": 40.6222,
    "Longitude": -75.3908,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 7251,
    "ClientCode": "C6213",
    "PSCName": "HNL PSC West Chester",
    "AddressLine": "1239 West Chester Pike",
    "AddressLine2": "Goshen Crossing",
    "AddressLine3": null,
    "County": "Chester County",
    "Country": null,
    "City": "West Chester",
    "State": "PA",
    "ZipCode": "19382",
    "Phone": "(484) 947-0921",
    "Fax": "(484) 999-8460",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:00 p.m.  Tuesday: 7:00 a.m. to 4:00 p.m.  Wednesday: 7:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:00 p.m.</span>  Friday: 7:00 a.m. to 4:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_westchester.jpg",
    "Distance": -1,
    "Latitude": 39.9682,
    "Longitude": -75.5567,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6248,
    "ClientCode": "C5078",
    "PSCName": "HNL PSC West Reading",
    "AddressLine": "525 Penn Avenue",
    "AddressLine2": "West Reading Shopping Center",
    "AddressLine3": null,
    "County": "Berks County",
    "Country": null,
    "City": "West Reading",
    "State": "PA",
    "ZipCode": "19611",
    "Phone": "(610) 927-5102",
    "Fax": "(610) 927-5106",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: 7:00 a.m. to 5:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 5:00 p.m.</span>  Friday: 7:00 a.m. to 5:00 p.m.  Saturday: 7:00 a.m. to 11:00 a.m.  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_reading.jpg",
    "Distance": -1,
    "Latitude": 40.3366,
    "Longitude": -75.9484,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Closed",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 9994,
    "ClientCode": "C6460",
    "PSCName": "HNL PSC Whitehall",
    "AddressLine": "1280 Macarthur Road",
    "AddressLine2": "Suite 5",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Whitehall",
    "State": "PA",
    "ZipCode": "18052",
    "Phone": "(484) 357-6933",
    "Fax": "(484) 357-6934",
    "BussinessHours": "  Monday: 8:00 a.m. to 4:30 p.m.  Tuesday: Closed  Wednesday: Closed<span class=\"today\">  Thursday: Closed</span>  Friday: Closed  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_reading.jpg",
    "Distance": -1,
    "Latitude": 40.9745,
    "Longitude": -75.2751,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6208,
    "ClientCode": "C5040",
    "PSCName": "HNL PSC Willow Street",
    "AddressLine": "2850 Willow Street Pike",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lancaster County",
    "Country": null,
    "City": "Willow Street",
    "State": "PA",
    "ZipCode": "17584",
    "Phone": "(717) 435-8061",
    "Fax": "(717) 435-8284",
    "BussinessHours": "  Monday: 6:30 a.m. to 4:30 p.m.  Tuesday: 6:30 a.m. to 4:30 p.m.  Wednesday: 6:30 a.m. to 4:30 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 4:30 p.m.</span>  Friday: 6:30 a.m. to 4:30 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_willowst.jpg",
    "Distance": -1,
    "Latitude": 39.9745,
    "Longitude": -76.2751,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "15",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6359,
    "ClientCode": "C5185",
    "PSCName": "HNL PSC Wind Gap",
    "AddressLine": "1411 Jacobsburg Road",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Northampton County",
    "Country": null,
    "City": "Wind Gap",
    "State": "PA",
    "ZipCode": "18091",
    "Phone": "(610) 452-3020",
    "Fax": "(610) 452-3022",
    "BussinessHours": "  Monday: 6:30 a.m. to 3:00 p.m.  Tuesday: 6:30 a.m. to 3:00 p.m.  Wednesday: 6:30 a.m. to 3:00 p.m.<span class=\"today\">  Thursday: 6:30 a.m. to 3:00 p.m.</span>  Friday: 6:30 a.m. to 3:00 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_windgap.png",
    "Distance": -1,
    "Latitude": 40.8311,
    "Longitude": -75.3018,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "10",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 6763,
    "ClientCode": "C5701",
    "PSCName": "HNL PSC Wyomissing",
    "AddressLine": "1320 Broadcasting Road",
    "AddressLine2": "Ste. 109",
    "AddressLine3": null,
    "County": "Berks County",
    "Country": null,
    "City": "Wyomissing",
    "State": "PA",
    "ZipCode": "19610",
    "Phone": "(610) 898-4833",
    "Fax": "(484) 577-4734",
    "BussinessHours": "  Monday: 7:00 a.m. to 4:00 p.m.  Tuesday: 7:00 a.m. to 4:00 p.m.  Wednesday: 7:00 a.m. to 4:00 p.m.<span class=\"today\">  Thursday: 7:00 a.m. to 4:00 p.m.</span>  Friday: 7:00 a.m. to 4:00 p.m.  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_Wyomissing.jpg",
    "Distance": -1,
    "Latitude": 40.3521,
    "Longitude": -75.9844,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  },
  {
    "ClientID": 9995,
    "ClientCode": "C6461",
    "PSCName": "HNL Southside",
    "AddressLine": "2268 South 12th Street",
    "AddressLine2": "",
    "AddressLine3": null,
    "County": "Lehigh County",
    "Country": null,
    "City": "Allentown",
    "State": "PA",
    "ZipCode": "18103",
    "Phone": "(610) 424-2211",
    "Fax": "(610) 424-2000",
    "BussinessHours": "  Monday: 7:00 a.m. to 5:00 p.m.  Tuesday: 7:00 a.m. to 5:00 p.m.  Wednesday: Closed<span class=\"today\">  Thursday: Closed</span>  Friday: Closed  Saturday: Closed  Sunday: Closed",
    "Disclaimer": null,
    "ImagePath": "https://secureportal.healthnetworklabs.com/Apps/Content/PSCImages/psc_reading.jpg",
    "Distance": -1,
    "Latitude": 40.571,
    "Longitude": -75.4741,
    "Active": null,
    "CurrentWaitTime": 0,
    "WaitTimeDescription": "5",
    "ShowWaitTime": false,
    "Response": null,
    "AdditionalMessage": null,
    "Holidays": null,
    "PSCCurrentStatusMessage": "Open",
    "CompanyHolidayResponse": null
  }
];
  }
  public get stores_list(): any[] {
    return this.stores;
  }
  public set stores_list(stores) {
    this.stores = stores;
  }
}
